version: '3.7'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  asmodee-server:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "9222:9222"

  asmodee-react:
    build: ../asmodee-werewolf-react
    ports:
     - "80:80"
    


